version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  animal-detector-resnet50:
    lang: python3-http-debian
    handler: ./animal-detector-resnet50
    image: keidikei/animal-detector-resnet50:latest

